### ISSUE TITLE
Migrate flask tests

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#101]
**Description of feature/enhancement**
The _test.py_ file is getting a bit cluttered, move the flask related tests to their own file called _flask_tests.py_.

**Description of implementation**
Migrate the _TestPreprocess_ and _TestRouting_ classes into the new file.

**Why this is a good feature/enhancement**
Would be easier to keep track of tests if they are in their own separate files.

**Additional context**
Do not delete test.py or your PR will fail during integration. Leave test.py as is and only migrate the required test classes to the new file

**Comment by koushikjoshi** [comment]
I tried to execute main.py and it shows this:
D:\Github\NBA-Search>python main.py train
Removing previous training instance
No previous instance detected

**Comment by skekre98** [comment]
Not a bug, it is just trying to remove a previous training instance for a model that no longer exists. Also might be in our interest to refactor `main.py` entirely since a lot of the modelling has changed. I will open an issue for this. As for this issue, it is currently being working on in #102
