### ISSUE TITLE
Refactor main.py to remove excess blocks

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#104]
**Description of feature/enhancement**
`main.py` still contains components to train models and remove the old `chatterbot` training instance even though this is outdated. This needs to be removed.

**Description of implementation**

This component is looking to delete an older training instance of `chatterbot` that no longer exists(Remove it).
https://github.com/skekre98/NBA-Search/blob/756bf8c023a43c6cce4996fec82a874859a12fa6/main.py#L15-L20
 

This is training the query classification model even though this is done in the setup script. You can go ahead and remove it.
https://github.com/skekre98/NBA-Search/blob/756bf8c023a43c6cce4996fec82a874859a12fa6/main.py#L31-L32

**Why this is a good feature/enhancement**
No need for this excess code.

**Additional context**
n/a

**Comment by skekre98** [comment]
@koushikjoshi would you want to work on this?

**Comment by koushikjoshi** [comment]
> @koushikjoshi would you want to work on this?

Sure! On it already
