### ISSUE TITLE
Create a better Chatbox

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#111]
**Description of feature/enhancement**
Current chatbox is poorly designed. If a front end expert would like to take up designing a new chatbox, that would be greatly appreciated!

**Description of implementation**
Improve on this chatbox:
<img width="986" alt="Screen Shot 2020-11-03 at 4 30 58 PM" src="https://user-images.githubusercontent.com/18124349/98055381-339ab480-1df2-11eb-9502-05d021358c5b.png">
 Implementation is up to you 😄 

**Why this is a good feature/enhancement**
Could use a better chatbox to fit with website.

**Additional context**
n/a

**Comment by kelaaron** [comment]
Hi @skekre98, is this issue still available? If so myself and @sbeinlich would love to work on it

**Comment by skekre98** [comment]
Hi @kelaaron, it is still available. I'll go ahead and assign the issue over to you two. My front end knowledge is pretty poor so it would be greatly appreciated if you guys could take lead on this 😃 . Much appreciated!

**Comment by iamalexk** [comment]
Hey @skekre98, I know you assigned this issue a couple of days ago, but do you think I could take a shot at it as well?
