### ISSUE TITLE
Improve documentation in Inference Network class

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#113]
**Description of feature/enhancement**
Current documentation in `../inference/inference_network.py` is lacking. Could use better documentation. 

**Description of implementation**
See `../modules/scraper.py` for examples of documentation. Should be in following format:
```python
"""
Function description
----------
input : type
    description of input parameter
Returns
-------
output : type
    description of output parameter
"""
```

**Why this is a good feature/enhancement**
Better documentation would make it easier for first time contributors to jump right into code base.

**Additional context**
n/a

**Comment by Florent18570** [comment]
Hello can you affiliate me this issue ?

**Comment by smwitkowski** [comment]
Just added some documentation for this file in #152.

**Comment by mohsinzafaruk1996** [comment]
Is this PR still being worked on, if not I would like to contribute :)

**Comment by plnancy** [comment]
Update inference_network.py

**Comment by V3NN0W** [comment]
Hello there , this PR is it still open I would like to contribute ?

**Comment by skekre98** [comment]
Hi @V3NN0W, apologies this issue was meant to be closed a while ago.

**Comment by V3NN0W** [comment]
Hello skekre98,

 thank you for your quick response.  Apart from this topic I wanted to see
with you, maybe you know more than me, but why not integrated a video
player which would show the important moments or actions of a match when
clicked?  Of course it goes without saying that we need to create a clean
YouTube channel for the site, but that sounds good to me, I'd love to hear
from you.

I wish you a good evening, take care of yourself.

Cordially

V3NN0W.
