### ISSUE TITLE
Improve documentation in Info Node class

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#114]
**Description of feature/enhancement**
Current documentation in `../inference/infonode.py` is lacking. Could use better documentation. 

**Description of implementation**
See `../modules/scraper.py` for examples of documentation. Should be in following format:
```python
"""
Function description
----------
input : type
    description of input parameter
Returns
-------
output : type
    description of output parameter
"""
```

**Why this is a good feature/enhancement**
Better documentation would make it easier for first time contributors to jump right into code base.

**Additional context**
n/a

**Comment by AColocho** [comment]
Ill take this one. If I may suggest, can we change the doc string to this:
`
"""
Function description
----------
input : type
    description of input parameter
-------
Returns
output : type
    description of output parameter
"""
`

**Comment by skekre98** [comment]
Sure, that would be great! There is a plan to add a code formatter such as [Black](https://github.com/psf/black) down the road so that will take care of formatting the comments as well. At the moment, I was hoping to have more verbose docs for each of the important classes such as the nodes.
