### ISSUE TITLE
Joblib import faillure

### ISSUE THREAD

**Issue by Pokiharena** [skekre98/NBA-Search#117]
**Describe the bug**
The import call for the Joblib package seems to have changed.

**To Reproduce**
1. clone the repository
2. run the setup command `./setup.sh'

**Expected behavior**
When running the `train_models` the code fails to import the joblib library of the corresponding python script `query_classifier.py`
**Screenshots**
![image](https://user-images.githubusercontent.com/26529448/98176236-6d55e300-1ef8-11eb-9ad7-60dd7da1de8c.png)

**Desktop (please complete the following information):**
 - Python: 3.8.5
- scikit-learn: 0.22.2

**Additional context**
A quick fix for the import while be to replace the following line:
```python
from sklearn.externals import joblib
```
By this one: 
```python
import joblib
```
According to this  [link](https://stackoverflow.com/questions/61893719/importerror-cannot-import-name-joblib-from-sklearn-externals) the former is deprecated and the later is required since scikit-learn: 0.21.

But I don't have an explanation for why I have this issue and not other contributors.

**Comment by skekre98** [comment]
Hi @Pokiharena,thanks for creating this issue. I see no reason to use the sklearn joblib vs utils, so please feel free to update `query_classifier.py` with your fix. I'll go ahead and assign this issue to you.

**Comment by Nahoyhp** [comment]
This is a strange issue because for me, I only got flagged out in `inference/inference_network.py`.
I will make the PR that changes the two imports for `import joblib`.
