### ISSUE TITLE
Grammatical errors in Stat Node response

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#123]
**Describe the bug**
Quite a few grammatical errors in responses being received from Stat Node.

Examples: 

https://github.com/skekre98/NBA-Search/blob/f7939c9176001c4e9ecfa423eaf0dee25b077a08/inference/statnode.py#L26

https://github.com/skekre98/NBA-Search/blob/f7939c9176001c4e9ecfa423eaf0dee25b077a08/inference/statnode.py#L30

**To Reproduce**
1. Open the chatbox
2. Make a stat query
3. A few responses will have grammatical errors

**Expected behavior**

Grammatically correct reponses

**Screenshots**
![](https://user-images.githubusercontent.com/45439410/98996402-cb8a5380-2500-11eb-9bfc-ab39b92d1fe7.png)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**
n/a

**Comment by Florent18570** [comment]
Hello, I will try to work to solve this problem.

**Comment by skekre98** [comment]
@Florent18570 thanks! That would be great 😄

**Comment by abhijeetsharma200** [comment]
Hi, I maybe wrong here but isn't the issue here in the values of the variables `name, stat` rather than the grammar of the sentence?

**Comment by skekre98** [comment]
@abhijeetsharma200, yes that was a different issue entirely, but it was fixed in #126
