### ISSUE TITLE
Misclassification of stat label in Stat Node

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#124]
**Describe the bug**
The Stat Node is currently incorrectly classifying some stat labels.

```
Query: "How many rebounds will Lebron get?"
Response: "Couldn't you Google that? Well since we're already here: 3-point field goal attempts per game has Lebron of 4.3"
```

**To Reproduce**
1. Open the chatbox
2. Make a stat query
3. See incorrect stat classification

**Expected behavior**
```
Query: "How many rebounds will Lebron get?"
Response: "Couldn't you Google that? Well since we're already here: rebounds per game has Lebron of <val>"
```

**Screenshots**
![](https://user-images.githubusercontent.com/45439410/98996402-cb8a5380-2500-11eb-9bfc-ab39b92d1fe7.png)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**
Likely an issue with the 'extract_stat` function
https://github.com/skekre98/NBA-Search/blob/f7939c9176001c4e9ecfa423eaf0dee25b077a08/inference/statnode.py#L87-L106

**Comment by AidanKenney** [comment]
Hi, I'm interested in working on this. Should I wait for assignment or go ahead and start? Thanks!

**Comment by skekre98** [comment]
@AidanKenney, that would be great! I'll go ahead and assign the issue over to you.

**Comment by AidanKenney** [comment]
@skekre98 I think I'm zero-ing in on where the issue is, but I'm having trouble debugging without being able to see what "nlp" and "similarity" are doing to the chat entries. I've tried printing, but that doesn't show me anything. I'm sorry if this is something obvious, but have any advice?

**Comment by skekre98** [comment]
@AidanKenney sorry about the lack of documentation. I've been meaning to get on that. `self.nlp` is the spacy english model class that is doing all the natural language processing. I'm not sure what you are looking for exactly, but there are a lot of built in functions in spacy that allow you to analyze text that has been processed. Here is a helpful guide about how to use spacy: https://spacy.io/usage/spacy-101. In our case, we are using spacy for entity extraction such as names and stat type. 

At a high level, you can think of spacy as a tool to perform common NLP related tasks.
Ex.
```python
import spacy

nlp = spacy.load("en_core_web_md")
text = "This is just some random text"

# create spacy doc to perform NLP tasks
doc = nlp(text)

# entity extraction
for entity in doc.ents:
    # do stuff/test with the entity
```

Hope this helps! Let me know if you have any other questions 😄

**Comment by AidanKenney** [comment]
Thank you! I will look more into spacy soon.

I have a hunch that the issue is with the "similarity" portion of the function. The reason being that writing "total rebounds" instead of just "rebounds" gives you the answer you would expect, I imagine because "total rebounds" is included word-for-word in the total_stat_map dictionary. 

```
Query: "How many total rebounds will Lebron get?"
Response: "Lebron has total rebounds per game of 7.4, impressive isn't it?"
```

The problem then is that for some reason, "3-point field-goal attempts" is being considered more similar to "rebounds" than to "total rebounds/offensive rebounds/defensive rebounds." I'll look more into how spacy processes similarity and what the sim thresholds mean, since obviously anything to do with rebounds would be better than 3-pointers.

**Comment by AidanKenney** [comment]
After playing around with spaCy's similarity method, I see there's a really strange comparison between "rebound" and "3-point" -- it puts them at 0.99999 similarity, above the 0.7 threshold in the StatNode class. Gonna keep looking into it!

```py
import spacy

nlp = spacy.load("en_core_web_md")  # make sure to use larger model!
tokens = nlp("rebounds 3-point")

for token1 in tokens:
    for token2 in tokens:
        print(token1.text, token2.text, token1.similarity(token2))
```
```
rebounds rebounds 1.0
rebounds 3-point 0.9999999
3-point rebounds 0.9999999
3-point 3-point 1.0
```

**Comment by skekre98** [comment]
> After playing around with spaCy's similarity method, I see there's a really strange comparison between "rebound" and "3-point" -- it puts them at 0.99999 similarity, above the 0.7 threshold in the StatNode class. Gonna keep looking into it!
> 
> ```python
> import spacy
> 
> nlp = spacy.load("en_core_web_md")  # make sure to use larger model!
> tokens = nlp("rebounds 3-point")
> 
> for token1 in tokens:
>     for token2 in tokens:
>         print(token1.text, token2.text, token1.similarity(token2))
> ```
> 
> ```
> rebounds rebounds 1.0
> rebounds 3-point 0.9999999
> 3-point rebounds 0.9999999
> 3-point 3-point 1.0
> ```

@AidanKenney this is actually really great to know! In fact, I think you may have identified the bug. I see no reason we have to use spacy for string similarity, so let's think of other options that may be better suited here. Some options that I have found are the following:
* [FuzzyWuzzy](https://github.com/seatgeek/fuzzywuzzy) - python library specifically for string matching.(We are actually already using this in the Scraper API)
https://github.com/skekre98/NBA-Search/blob/3497f5b8053783e123dc36d52b762493825823df/modules/scraper.py#L207
* [jellyfish](https://github.com/jamesturk/jellyfish) - python library for string matching with multiple built in string comparison algorithms.

Feel free to test them out and see which one you think we should use 😄

**Comment by AidanKenney** [comment]
@skekre98 Sounds good! Thanks for putting this together.
