### ISSUE TITLE
Improve Query Class

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#13]
**Description of feature/enhancement**
Find a way to handle query processing more efficiently. Currently text is just being passed into _InferenceNetwork_. 

**Description of implementation**
This will be receiving the user message from the chatbot and should leave an open implementation to handle a wide set of query classes.

**Why this is a good feature/enhancement**
This is the main backend component of the chatbot.

**Additional context**
n/a

**Comment by anjoshigor** [comment]
Hi! :hand: 

What would you consider that could be done to improve efficiency? I'm available to contribute, but I would like to know which text processing I can do to help in this case.

Thanks in advance.

**Comment by skekre98** [comment]
Hi @anjoshigor 

The current implementation isn't doing any preprocessing when feeding the text into the Inference Network. If you could add a filter method to perform operations like stripping whitespaces or removing useless characters such as @,#,etc... that would be really helpful 😊. I will go ahead and assign the issue to you.

Thanks!

**Comment by skekre98** [comment]
Closing for low priority
