### ISSUE TITLE
Remove usage of os.system and refactor to use modules

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#132]
**Description of feature/enhancement**
Currently there are quite a few uses of `os.system` in the repository. These should be converted module implementations.
https://github.com/skekre98/NBA-Search/blob/3497f5b8053783e123dc36d52b762493825823df/main.py#L19-L27

**Description of implementation**
Current implementation:
```python
os.system('python3 visualize.py'`)
```

Better implementation:
```python
import visualize

visualize.main()
```

**Why this is a good feature/enhancement**
The current implementation is spawning new processes for every `os.system` call which is not very compute friendly. It would be better to use the same process as the original call by using modules instead of os calls.

**Additional context**
n/a

**Comment by abhijeetsharma200** [comment]
Hi, I had like to work on this if it is available.

Also from what I understand Unittest needs a command line input to run. So I am not sure how to implement modules for lines 19-23.

**Comment by skekre98** [comment]
@abhijeetsharma200 that would be great! We can ignore the command line input for now. You will however need to add some kind of `run` method in the test files that you will call from `main.py`.

**Comment by abhijeetsharma200** [comment]
Hey, so I have implemented modules for `sys.argv[1] == "run"` and `sys.argv[1] == "data"`. However, I am still unsure how to implement the `run` method. So, I am currently looking at [https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-vii-unit-testing-legacy](url). Please let me know if there are any better resources.

**Comment by skekre98** [comment]
Hi @abhijeetsharma200, "run" is actually already part of the `unittest` library. You would simply need to import the test classes from each file and run them with the unittest library. Here is a good reference on how it works: https://stackoverflow.com/questions/31559473/run-unittests-from-a-different-file

In our case, you would be importing classes such as `TestPreprocess`, `TestRouting`, etc...
