### ISSUE TITLE
Standings display issue on Firefox

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#138]
**Describe the bug**
The standings are not being displayed correctly on the predictions page on Firefox.

![image](https://user-images.githubusercontent.com/18124349/101962226-75bcd000-3bc0-11eb-8e59-54ca5ef6bd0c.png)

**To Reproduce**
1. Run the web app
2. Open the app in Firefox
3. Open the **Predictions** page under **Insights**
4. Scroll down to standings

**Expected behavior**
![image](https://user-images.githubusercontent.com/18124349/101962304-ae5ca980-3bc0-11eb-97b1-9bad74616add.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: latest

**Additional context**
n/a

**Comment by AidanKenney** [comment]
Hi @skekre98, I'm happy to look into this. So I'm clear, is the problem with the win/loss stats, the dividing lines on the table not showing up, or both? And for the stats, which is the the correct one:  "Lakers: 20 wins, 20 losses" or "Lakers, 52 wins, 19 losses"?

**Comment by skekre98** [comment]
Hi @AidanKenney, it is the dividing lines not showing up. The standings function was merge in a separate PR. I'll go ahead and assign the issue over to you 😄

**Comment by AidanKenney** [comment]
Hi @skekre98,  I've been looking into this and it's a really weird Firefox bug that goes back quite a while. Basically, adding "background-clip: padding-box" fixes it when using inspector tools, but if you add that to the CSS, it won't show up in the browser. It seems Firefox paints over borders under certain conditions. 

I haven't found a full fix yet, but here is some of the documentation I've been looking at:
https://bugzilla.mozilla.org/show_bug.cgi?id=688556
https://stackoverflow.com/questions/7517127/borders-not-shown-in-firefox-with-border-collapse-on-table-position-relative-o/7519866

Will keep trying! Let me know if you have any ideas.

**Comment by skekre98** [comment]
I see, could it be an issue with overriding the cache in your browser? Or is the issue that Firefox is overriding `background-clip: padding-box` when the CSS is being interpreted?

**Comment by AidanKenney** [comment]
Good call! I cleared the cache and found it to be working as desired. I also removed a max-width property from the bootstrap styling that was making the team name column wrap/bunch up in Firefox, unlike the display in Chrome.

**Comment by skekre98** [comment]
Fixed in #143
