### ISSUE TITLE
Missing Chat Window

### ISSUE THREAD

**Issue by Nahoyhp** [skekre98/NBA-Search#142]
**Describe the bug**

**To Reproduce**
1. Clone the repository.
2. Run "./setup.sh"
3. Run `python3 main.py run`
4. Click on the `Let's Chat`

**Expected behavior**
There should be a chat window to talk to the bot.

**Screenshots**
Missing chat window.

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
![image](https://user-images.githubusercontent.com/54650877/102497987-59370100-40b4-11eb-8a6e-acde19524b2f.png)

**Comment by skekre98** [comment]
This actually isn't a bug. The entire window is the chatbox. The input is at the bottom of the screen 😄 
<img width="1678" alt="Screen Shot 2020-12-17 at 12 44 36 PM" src="https://user-images.githubusercontent.com/18124349/102541863-d0917400-4065-11eb-98d9-d04c6a044b6e.png">

However I do think it would be useful to make the window sizes dynamic. This has been an ongoing problem in front-end. In fact, #45 is a very similar issue. 

If this is something you would be interested in taking up, let's create a new issue for making window rendering more dynamically in sync with the browser.
