### ISSUE TITLE
Duplicate values in query.csv and text_data.py:alltime_player_list

### ISSUE THREAD

**Issue by AColocho** [skekre98/NBA-Search#156]
**Describe the bug**
Discovered duplicate values in query.csv and in the list alltime_player_list in the file text_data.py

**To Reproduce**
1. Go to query.csv and search "how are you"
1. Go to text_data.py and search "Chris Wright"

This is not an extensive list, just an example of a duplicate value.

**Expected behavior**
No duplicate values.

**Comment by skekre98** [comment]
Hi @AColocho, sorry for my absence. This is a good catch, feel free to work on it :)

**Comment by AColocho** [comment]
No problem! I actually have a pull request open associated with this. #157
