### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib' due to scikit-learn deprecation

### ISSUE THREAD

**Issue by RamParameswaran** [skekre98/NBA-Search#19]
'sklearn.externals.joblib' was deprecated in v0.23, resulting in ModuleNotFoundError. 
(see related issue https://github.com/skggm/skggm/issues/124).

I recommend updating requirements.txt to specify the scikit-learn=0.22.2
Unless there is specific functionality desired from v0.23?

**To Reproduce**
1. pip install -r requirements.txt
2. python main.py run
3. see error

```
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from modules.query import Query
  File "/home/ram/Dropbox/My Projects/NBA-Search/modules/query.py", line 3, in <module>
    from inference.inference_network import InferenceNetwork
  File "/home/ram/Dropbox/My Projects/NBA-Search/inference/inference_network.py", line 2, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/home/ram/.python-environments/nba-search/lib/python3.7/site-packages/sklearn/externals/__init__.py)
```

**Comment by skekre98** [comment]
Thank you! I have pushed the fix to master. I'll go ahead and close the issue.
