### ISSUE TITLE
Add NBA Standings section in predictions web page

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#21]
**Description of feature/enhancement**
Add a component to show NBA standings for eastern and western conference.

**Description of implementation**
Add component under the NBA Playoffs block. Can keep the data in the standings static for now. Only requires update to /templates/predictions.html.

**Why this is a good feature/enhancement**
Would be nice to have a component to show NBA standings. This will later be updated to a more automated process through web scraping like playoffs bracket is now.

**Additional context**
n/a

**Comment by MohammedBajuaifer** [comment]
Hi, @skekre98 I would like to work on this issue if that's good.

Changes should be made to the frontend and the data is static for now, right?

**Comment by skekre98** [comment]
Yes, please create separate standings for east and west under playoffs. Can you keep it in the format of **team name** **wins** and **losses**. I will go ahead and assign the issue to you, thanks 😄.

**Comment by MohammedBajuaifer** [comment]
Hi @skekre98, forgot to ask is there a specific design on your mind or I just follow the design of the website and see where it gets me

**Comment by MohammedBajuaifer** [comment]
Hey @skekre98, I've started working on this feature but I would like your comments regarding the design/structure of it. Here is a sample of what I did so far!


![image](https://user-images.githubusercontent.com/29784211/94993100-3dcd5700-0597-11eb-9b72-e82f2f0184ad.png)

**Comment by skekre98** [comment]
@MohammedBajuaifer this looks awesome! Could you make the background of the standings white like the playoff bracket? Besides that this is perfect. I'm guessing they are both tables so we can add as many rows as we'd like right?

**Comment by MohammedBajuaifer** [comment]
Hey @skekre98, Sure thing! Yes we can add as many rows as we want, was thinking we could make it dynamic once we scrape the standings

**Comment by skekre98** [comment]
Awesome, I'll open an issue for automating the standings data once your changes are in!

**Comment by MohammedBajuaifer** [comment]
Here! I have opened a PR 

![image](https://user-images.githubusercontent.com/29784211/94999662-90bd0380-05c3-11eb-9a25-53bbb9145058.png)

**Comment by skekre98** [comment]
Awesome! I will go ahead and close this issue, and we can discuss automation of this workflow in #38 if you'd like 😃
