### ISSUE TITLE
Website Header Reformatting

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#34]
**Description of feature/enhancement**
Would be a good idea to change the arrangement of the website header. Currently the order reads (Home, Github, About Us, Insights). The Github section is unnecessary as there is already a contribute button on every page of the website. The the header should be updated to a more prioritized order of (Home, Insights, About Us, Contributors).

**Description of implementation**
Everything in `../templates/` will need to be updated to suite this format. As far at the contributors section, link it to the repo contributors page: https://github.com/skekre98/NBA-Search/graphs/contributors

**Why this is a good feature/enhancement**
Github header is unnecessary given contribute button already exists. 

**Additional context**
No need to change any of the material on the actual pages, just rearrange the list items and create one for contributors.

**Comment by MohammedBajuaifer** [comment]
Hi @skekre98, I can work on this. Also, isn't better to have a base.htm file for the header + foorer

**Comment by MohammedBajuaifer** [comment]
Hey @skekre98, i can work on this!

**Comment by MohammedBajuaifer** [comment]
Hey @skekre98, I can work on this!

Also, Isn't better to have a base.html for the header & footer instead of writing them in every file

**Comment by skekre98** [comment]
@MohammedBajuaifer I am not that familiar with HTML 😅, but that definitely sounds like a better implementation. Was this incorporated into #37?

**Comment by MohammedBajuaifer** [comment]
Yes!

**Comment by skekre98** [comment]
Cool, merged the PR 😄. Will go ahead and close this issue.
