### ISSUE TITLE
Automate the creation of NBA standings in predictions page

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#38]
**Description of feature/enhancement**
The current version of NBA standings is in static format. It would be better to automate this process to we don't have to manually update standings. 

**Description of implementation**
There is already a function to scrape standings: https://github.com/skekre98/NBA-Search/blob/20981aa0274be9109b6cd2e91c3d9d0e2203d4a9/modules/scraper.py#L139
Will only require passing standings list when rendering predictions. 

**Why this is a good feature/enhancement**
Will no longer need to manually update standings.

**Additional context**
There is also currently a bug in the `get_standings` function with index creation that will need to be addressed.

**Comment by MohammedBajuaifer** [comment]
Hey @skekre98, would love to continue working on the standings!

**Comment by skekre98** [comment]
@MohammedBajuaifer that would be great! Thanks for seeing the entire component end to end 😃

**Comment by MohammedBajuaifer** [comment]
Happy to do so! 😄

**Comment by MohammedBajuaifer** [comment]
Hey @skekre98!, sorry for taking abit of time on this task.

**Comment by skekre98** [comment]
@MohammedBajuaifer any update on this issue?

**Comment by iamalexk** [comment]
@skekre98 Hey I plan on working on #111 and #45 but could I also try this issue if I find the time?

**Comment by skekre98** [comment]
@iamalexk Sure, thanks for taking so many issues!

**Comment by iamalexk** [comment]
@skekre98 working on this issue and turns out the get_standings function doesn't actually work. Was implementing that function a part of this issue or was this issue not known before. I'll try to fix the get_standings function but just wanted to let you aware of the issue. Also, I'm not familiar with web scraping so please bare with me as I try to fix the get_standings functions.

**Comment by skekre98** [comment]
I was definitely not aware of this issue. Can you describe the bug and also possibly create a separate issue for tracking purposes. This is the first I am hearing about `get_standings` not working.

**Comment by iamalexk** [comment]
@skekre98 I've fixed the get_standings function and automated the standings already so no need to open another issue. I'll be sending a pull request later today after fixing some configuration issue with my github

**Comment by skekre98** [comment]
@iamalexk awesome, really appreciate it! I'll go ahead and update this issue to include the bug fix.

**Comment by iamalexk** [comment]
@skekre98 just submitted pull request to resolve this issue. I accidentally included some changes to another file that I needed to make in order to run locally, so you can ignore those.
