### ISSUE TITLE
generate_random_response function: StatNode

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#41]
**Description of feature/enhancement**
Add a function to generate a random response for StatNode. Currently there is a list of responses in the _response_ function:
https://github.com/skekre98/NBA-Search/blob/86e9d395b9e5a1df4df2142984aeeb2a5f55c1cd/inference/statnode.py#L29-L35
These all should be moved to `generate_random_response` along with the new responses you create. 

**Description of implementation**
Pass _name_, _stat_, and _stat_val_ into this function
```
def response(self):
    return self.generate_random_response(name, stat, stat_val)

def generate_random_response(self, name, stat, stat_val):
      # TODO
```

**Why this is a good feature/enhancement**
Cleaner implementation to keep _response_ function less clustered. 

**Additional context**
Try to have at least 10 responses in this function. Feel free to have more!

**Comment by gabesduhbear** [comment]
I can work on this!

**Comment by skekre98** [comment]
Cool, thanks! I'll go ahead and assign the issue over to you.

**Comment by Ervin66** [comment]
is this issue still open?

**Comment by skekre98** [comment]
@Ervin66 Yes this is still open. Would you like me to assign it to you?

**Comment by Ervin66** [comment]
yes please
