### ISSUE TITLE
generate_random_reponse function: RankNode

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#42]
**Description of feature/enhancement**
Add a function to generate a random response for RankNode. Currently there is a list of responses in the _response_ function:
https://github.com/skekre98/NBA-Search/blob/86e9d395b9e5a1df4df2142984aeeb2a5f55c1cd/inference/ranknode.py#L51-L57
These all should be moved to `generate_random_response` along with the new responses you create. 

**Description of implementation**
Pass _max_entity_, _min_entity_, and _stat_ into this function
```
def response(self):
    return self.generate_random_response(max_entity, min_entity, stat)

def generate_random_response(self, max_entity, min_entity, stat):
      # TODO
```

**Why this is a good feature/enhancement**
Cleaner implementation to keep _response_ function less clustered. 

**Additional context**
Try to have at least 10 responses in this function. Feel free to have more!

**Comment by gabesduhbear** [comment]
Sorry for not letting you know earlier, but I just finished this enhancement and made a PR.

**Comment by skekre98** [comment]
Awesome, thanks!
