### ISSUE TITLE
Creating training data for InfoNode

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#44]
**Description of feature/enhancement**
Attempting to create a new node that will answer questions about chatbot(personal info, existential questions, etc.)

**Description of implementation**
Create a function in `../preprocess.py` which will create training data for a new class in `query_classifier` labeled "info". Create queries in the form on personal/existential questions. Refer to _generate_stat_queries_ and _generate_rank_queries__ for formatting.

**Why this is a good feature/enhancement**
This will allow us to create another class for chatbot responses.

**Additional context**
n/a

**Comment by modernfaust** [comment]
would love to work on this. Any pointers on how I might approach this?

**Comment by skekre98** [comment]
@modernfaust that would be great! I would recommend taking a look at the generate functions for the other two labels and keeping it in that format. As far as the actual questions, that is up to you ☺️. Ideally they should be personal questions. You can test to make sure the training data stays balanced by retraining the query classification model with `python query_classifier.py`. This will print out the accuracy of the trained model as well. Feel free to use this issue thread to communicate anything you come across.

**Comment by modernfaust** [comment]
would you like to me try implementing InfoNode?

**Comment by skekre98** [comment]
@modernfaust Yes, that would be great! I'll go ahead and close this issue. Feel free to create an issue for implementing InfoNode and assign it to yourself 😄

**Comment by skekre98** [comment]
InfoNode being worked on in #55
