### ISSUE TITLE
Authors page does not fill browser window

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#45]
**Describe the bug**
The footer portion of the authors page does not go to the bottom of the browser. Most likely an issue with the authors block not rendering far enough. 

**To Reproduce**

1. Run application with `python main.py run`
2. Visit application running on `localhost`
3. Select **About Us** in header

**Expected behavior**
The footer should render to the bottom of the browser.

**Screenshots**
<img width="1676" alt="Screen Shot 2020-10-09 at 12 56 59 PM" src="https://user-images.githubusercontent.com/18124349/95627477-224bcb80-0a31-11eb-9be0-cdf4d40e1af8.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: latest

**Additional context**
Make sure this is fixed for all browsers if possible. I noticed this issue on chrome.

**Comment by kelvin3127** [comment]
Hello, I am down to try if you let me fork

**Comment by skekre98** [comment]
@kelvin3127 that would be great! I'll assign this to you.

**Comment by kelvin3127** [comment]
Hello, i cant seem to get it to run on localhost:8080

**Comment by skekre98** [comment]
```
(home) NBA-Search sharvilkekre$ python main.py run
Removing previous training instance
No previous instance detected
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

@kelvin3127 it should run on port 5000

**Comment by kelvin3127** [comment]
Hello, I was able to get the server running, but when i make any changes to check if the problems is fixed, nothing happens on http://127.0.0.1:5001/, none of the changes are applied

**Comment by kelvin3127** [comment]
nvm got it working

**Comment by kelvin3127** [comment]
How are the styles being handled right now, the changes made in style.css arnt being applied and even when i try to inline style in home.html it is also not being applied

**Comment by skekre98** [comment]
Not sure, all styling is done by style.css. Perhaps you need to clear the cache on your browser? Check out https://stackoverflow.com/questions/2263096/css-file-not-refreshing-in-browser

**Comment by kelvin3127** [comment]
The cache is not the issue right now , the style sheets are not loading properly, it seems like you are getting it from another url, I have deleted the style.css file and the css on the webpage still shows the same even with it gone.

**Comment by kelvin3127** [comment]
I found out what the issue was, I changed the routing in app.py
app = Flask(__name__)

app = Flask(__name__, static_url_path='/static')

and the css lin tags into 
<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

<link rel="stylesheet" type="text/css" href="../static/css/style.css">

**Comment by skekre98** [comment]
@kelvin3127 your problem is most likely with  overriding cache. The fact that you deleted style.css and it still rendered means the previous stylesheets were likely still stored in cache.

```
<!-- themify CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/themify-icons.css')}}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <!-- author CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/author.css')}}">
```
These are the only stylesheets being used on the actual page. The first two are for icons/formatting. The following two are the actual styles for the web page for elements such as the header and author card respectively.

You can also remove  `app = Flask(name, static_url_path='/static')`, Flask defaults the static directory to `../static`.

**Comment by skekre98** [comment]
@kelvin3127 any update on this issue?

**Comment by iamalexk** [comment]
Hi @skekre98 if this issue is still open I'd love to give it a shot

**Comment by skekre98** [comment]
@iamalexk sure I'll assign this over to you.

**Comment by iamalexk** [comment]
Hey @skekre98 I haven't been able to replicate this issue when I run it locally. Has this issue already been resolved? I've included a screenshot of what the "About Us" page looks like when I run it.

![Uploading Screen Shot 2020-11-22 at 5.45.24 PM.png…]()

**Comment by skekre98** [comment]
@iamalexk That is very strange as this issue was never resolved. I am still seeing this problem on Firefox and I originally saw it on Chrome. What browser are you using?
![Screen Shot 2020-11-22 at 10 51 01 PM](https://user-images.githubusercontent.com/18124349/99935398-7aa30800-2d15-11eb-9e04-4a3e35f9f507.png)

**Comment by iamalexk** [comment]
@skekre98 I'm currently using Google Chrome on MacOS Catalina

**Comment by skekre98** [comment]
@iamalexk That's really strange, I'm still getting the issue on Chrome. Are you viewing the browser in Full Screen?

**Comment by kelvin3127** [comment]
I was recently using bootstrap to work on a project and i ran into the same problem with the little part at the bottom so I believe it might be a bootstrap CSS problem, but can probably fix using inline or overlap bootstrap CSS by using "!important"

**Comment by iamalexk** [comment]
@skekre98 I checked in full screen and my footer does seem to be reaching the bottom of the screen. @kelvin3127 when you run it, does the author page have the white space at the bottom?

**Comment by dksmith328** [comment]
Hi there. Is this issue still open? I may be able to resolve.

**Comment by skekre98** [comment]
@dksmith328, this issue was mostly resolved however there is still some issue with rendering on Firefox if you would like to look into it.

**Comment by dksmith328** [comment]
@skekre98, I was getting a small amount of white space on Chrome, Firefox, and Edge. I seem to have corrected the issue.
