### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#5]
**Description of feature/enhancement**

- Create the Blog HTML page for the website. Ideally there should be a blog object on the page with a title for the blog and an image to go along with it.  

**Description of implementation**

- The blog object should ideally either route to the blog or download the blog file for user. Think about how your implementation will fit into the rest of the website and where you could store the individual blogs for retrieval.

**Why this is a good feature/enhancement**

- It would be cool to create blogs for experiments run on NBA data. 

**Additional context**

- Feel free to create the blog page however you'd like. New ideas are always welcome!

**Comment by khintze1** [comment]
Is this issue still open?

**Comment by skekre98** [comment]
@khintze1 Yes, this is still open. Did you want me to assign it to you?

**Comment by Redbullrish** [comment]
Hell No I have most of it coded I just need to finish the sliding carousel if @khintze1 wants to help me implement that then ill push my code to git for him/her to take a look.

**Comment by khintze1** [comment]
If @Redbullrish  is almost finished I could test what they made? If not, if there are any other small issues I'd be happy to help.  I'm looking a project I can help contribute to for a class.  So anything small and code related I'd be happy to take a look.

**Comment by skekre98** [comment]
@khintze1 what is your background? I can create a small issue within that. There are quite a few apparent issues that I haven't opened yet.

**Comment by skekre98** [comment]
Being merged in #54.
