### ISSUE TITLE
InfoNode

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#55]
**Description of feature/enhancement**
This node will handle all queries related to relaying info regarding the chatbot. This node will answer any queries regarding personal info about the chatbot. No need to be too detail oriented 😄 

**Description of implementation**
Create a new file in `../inference/` labeled _infonode.py_ and implement all functionality there. Take a look at _statnode.py_ and _ranknode.py_ to see how other inference nodes have been implemented. (Feel free to discuss the content of the responses on this thread)

**Why this is a good feature/enhancement**
This will add more depth to the chatbot.

**Additional context**
You will first need to retrain the query classification model which you can do with `python query_classifier.py`. You will also need to update `../inference/inference_network.py` to pass queries labeled _info_ to the info node class.

**Comment by skekre98** [comment]
@modernfaust here is the issue for InfoNode if you'd like to work on it!

**Comment by modernfaust** [comment]
> 
> 
> @modernfaust here is the issue for InfoNode if you'd like to work on it!

gladly, I'll take this one!

**Comment by modernfaust** [comment]
After retraining the model and successfully passing info queries to InfoNode, how should the responses be structured? Should we select from a set of randomized responses depending on each query?

**Comment by skekre98** [comment]
I haven't put too much thought into it, but would be cool if the node "classified" the query in some way and then randomly selected from a list of responses. Check out _generate_random_response_ in ranknode.

**Comment by modernfaust** [comment]
Hey, currently trying to figure out a _"tag"_ combination exclusively for existential queries. This will help us classify the query. For example "Who are you?" is composed of ["WP", "VBP", "PRP"], whereas "What is Danny Green's average shooting?" is composed of [WP, VBZ, NNP, NNP, POS, JJ, NN]. 

Any guidance on this?

**Comment by skekre98** [comment]
Shouldn't this be handled by the query classifier? Why are we looking to manually classify the query? "Who are you" and "What is Danny Green's average shooting?" should be classified as _info_ and _stat_ respectively in _InferenceNetwork_. Do you mean actually identifying the existential query in info node?

**Comment by modernfaust** [comment]
You're right, the query is classified already as _info_ in InferenceNetwork, my mistake. We'll need to identify the type of existential query in InfoNode to select from a list of responses.

**Comment by skekre98** [comment]
I agree, this can be done in a number of ways. We could use `spacy` to check _pos_ and _tag_ to manually classify or even train another classifier called _info_classifier_ to do it for us. This will likely require some experimentation 😃

**Comment by modernfaust** [comment]
For now, I'll use `spacy` to manually classify based on _tag_ and _pos_.

**Comment by skekre98** [comment]
Being merged in #74
