### ISSUE TITLE
Implement ClusterStore API

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#59]
**Description of feature/enhancement**
Implement _ClusterStore_ at `../inference/cluster_store.py`.

**Description of implementation**
Functions are already predefined and just require implementation. Feel free to expand on current design. 
https://github.com/skekre98/NBA-Search/blob/db81f2da57ca848f3b75d35b946f7996c6e9e2e0/inference/cluster_store.py#L5-L10

- _data_: 2D array with values for each entity
- _entity_map_: Dictionary mapping entity name to given index in _data_
- _clustered_: Boolean to signify if data has been clustered or not
- _avg_similarity_: Float representing the average similarity between clusters(initialized to 0.0)
- _avg_distance_: Float representing the average distance between clusters(initialized to 0.0)

**Why this is a good feature/enhancement**
Will be very helpful in experiments and chatbot development.

**Additional context**
This is something that will definitely be expanded, so try to keep new functions you implement general purpose.

**Comment by skekre98** [comment]
Skeleton was built in #60. This only requires implementation.

**Comment by RaihanSabique** [comment]
Interesting problem. I want to work on it.
Is there any sample data of clusters and entity_map?
Redbullrish what's your progress?

**Comment by skekre98** [comment]
You can assume that clusters will originally start in a format similar to this:

```python
data = [
    [float, float, float],
    [float, float, float],
    [float, float, float],
]

entity_map = {
    0 : "entity1",
    1 : "entity2",
    2 : "entity3"
}
```

The lists in data may be of any size.

**Comment by Redbullrish** [comment]
@RaihanSabique I haven’t really made much progress as I’m trying to learn about clustering through this, if you feel like you can easily do this feel free to work on it and I can push what I have done so far once I finish work. Would appreciate if you could also explain thought process and comment to show exactly what you’re doing. Thanks!

**Comment by RaihanSabique** [comment]
@Redbullrish that's great if i can work from your existing work.
Sure, i will provide a scratch of the solution algorithms and steps ASAP here to understand the solution theoretically.
Please notify me when you push your existing code.

**Comment by RaihanSabique** [comment]
Hello @skekre98 
I'v completed k-means clustering. Can you please check and test it?
https://github.com/RaihanSabique/NBA-Search/blob/master/inference/cluster_store.py

**Comment by Redbullrish** [comment]
@RaihanSabique I can’t get kmeans to work could you explain?

**Comment by skekre98** [comment]
@RaihanSabique really well done. Thanks for going above and beyond with the extra getter functions! I have added a few comments to the PR, but besides that everything looks great 👍

**Comment by RaihanSabique** [comment]
> @RaihanSabique I can’t get kmeans to work could you explain?

If you want to understand the clustering techniques theoretically please read chapter-5 from this book [Data Mining Introductory and Advance Topics](https://www.amazon.com/Data-Mining-Introductory-Advanced-Topics/dp/0130888923). This is really a great book to understand the concepts of all clustering algorithms.
After that read the documents of [sklearn.cluster.KMeans](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html) for implementation. Hopefully, this two resources will give you clear perception about clustering methods.

**Comment by skekre98** [comment]
Will close this issue and split it into multiple other issues for remaining functions.
