### ISSUE TITLE
Implement build_pie in CSVBuilder

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#62]
**Description of feature/enhancement**
Implement a general purpose function to build a pie chart from a csv file assuming the last column is the label.

**Description of implementation**
https://github.com/skekre98/NBA-Search/blob/bf09e3319e444b311fdfff841f0a221fa2ad06bc/lab/csv_builder.py#L11-L13
This function should assume the last column is the label and create a pie chart to show what percentage of of the csv file each label makes up. This data should then be loaded into the _plot_(see Visualizer) variable. Functions such as display and clear have already been implemented in the parent class. This function should be implemented with the `matplotlib` library.

**Why this is a good feature/enhancement**
Will help in running data oriented experiments.

**Additional context**
n/a

**Comment by nrickles3** [comment]
@skekre98 I would be happy to take this issue.

**Comment by skekre98** [comment]
Thanks, I'll go ahead and assign it to you.

**Comment by nrickles3** [comment]
Clarification question, how will the relative values for each label be calculated?

Will the column before the label be the relative value of the label? Example:
    10,Label1
    10,Label2
    20,Label3
which would make Label1 25% (10/40), Label2 25% (10/40), and Label3 50% (20/40)?

Or will the data be based on the frequency of the label?
    data,Label1
    data,Label1
    data,Label1
    data,Label2
which would make Label1 75% (3/4) and Label2 25% (1/4)?

**Comment by skekre98** [comment]
The frequency of the label, such as the one you have described in the second example. You can assume the csv will be in the format:
```
-,-,-,label
-,-,-,label
-,-,-,label
```

**Comment by skekre98** [comment]
PR #88

**Comment by koushikjoshi** [comment]
@skekre98 Can I try my hand on this if it hasn't been done yet?

**Comment by skekre98** [comment]
Hi @koushikjoshi this is currently being worked on by @nrickles3. If you see an assignee, that means the issue is being worked on by them 😄

**Comment by koushikjoshi** [comment]
> Hi @koushikjoshi this is currently being worked on by @nrickles3. If you see an assignee, that means the issue is being worked on by them 😄
Oh! I'm sorry. This is going to take some getting used to 😆
