### ISSUE TITLE
Implement build_table in TableBuilder

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#68]
**Description of feature/enhancement**
Implement a general purpose function to build a table from the data being passed into the object such as _rows_ and _column_labels_.

**Description of implementation**
https://github.com/skekre98/NBA-Search/blob/b036b35aec8b4703ed899d6dd7fb0cbcb8c46d6f/lab/table_builder.py#L12-L14
This function should add the column labels and rows to the table. This data should then be loaded into the _plot_(see Visualizer) variable. Functions such as display and clear have already been implemented in the parent class. This function should be implemented with the `matplotlib` library.

**Why this is a good feature/enhancement**
Will help in running data oriented experiments.

**Additional context**
n/a

**Comment by samin-batra** [comment]
Hi @skekre98 , can you assign me to this issue? I'll work on it.

**Comment by skekre98** [comment]
Sure, thanks!

**Comment by skekre98** [comment]
`Visualizer`, it can be found in the _lab_ directory.

**Comment by samin-batra** [comment]
Got it. Are you planning to display the table as part of a bar plot/any other graphs? I assume that's the use given that you want to implement it in matplotlib. Correct?

**Comment by skekre98** [comment]
Not necessarily, think of this as a way to visualize scraped data in table format. I'd recommend actually removing the _row_  input from `__init__` and perhaps adding a function called `add_row` where you add a list to the list of "rows", then in `build_table` convert the rows into a matplotlib table. Ex.
```python
columns = ["Name", "Points"]
tb = TableBuilder(columns)
tb.add_row(["Jimmy Butler", 22.0]
tb.add_row(["Lebron James", 27.0]
tb.build_table()
```

See `graph_builder.py` for an example implementation. Feel free to add any extra functionality you think would be nice to have 😄

**Comment by samin-batra** [comment]
@skekre98 I have made a PR. Please review and let me know if there's anything else to include.

**Comment by skekre98** [comment]
@samin-batra thanks! I have raised some change requests. Let me know if you have any questions regarding them 👍
