### ISSUE TITLE
Implement build_bar_graph in GraphBuilder

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#72]
**Description of feature/enhancement**
Implement function to build bar graph in _GraphBuilder_ class.

**Description of implementation**
https://github.com/skekre98/NBA-Search/blob/38f129e338928572abbf9237d95b3dcc80a67773/lab/graph_builder.py#L38-L40
The function should add each bar in the list of bars to the plot. Think in terms of what would make for good visualization.

**Why this is a good feature/enhancement**
Will help with experimentation.

**Additional context**
Please add example usage of a bar graph in lab readme

**Comment by alee2233** [comment]
I would like to work on this issue. In the lab readme there is this snippet for the line graph:
```python
from lab.graph_builder import GraphBuilder

xlabels = ["Game 1", "Game 2", "Game 3", "Game 4", "Game 5", "Game 6"]
jb_line = [23.0, 25.0, 40.0, 22.0, 35.0, 12.0]
lbj_line = [25.0, 33.0, 25.0, 28.0, 40.0, 28.0]
gb = GraphBuilder(xlabels)
gb.add_line(jb_line, "Jimmy Butler")
gb.add_line(lbj_line, "LeBron James")
gb.build_line_graph()
gb.display()
```
Should this task include writing a similar bar graph section in the readme?

**Comment by skekre98** [comment]
@alee2233 Thanks, I will assign it to you. Yes, it would be great if you could also add example usage in the readme for bar graph. I'll update the issue.
