### ISSUE TITLE
InfoNode Test Cases

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#78]
**Description of feature/enhancement**
Create test cases for _InfoNode_ which can be found at `../inference/infonode.py`. Add new testcases to `test.py`. See the test cases for other nodes such as _RankNode_ and _StatNode_.

**Description of implementation**
```python
# Test cases for info node
class TestInfoNode(unittest.TestCase):

    # Method to testing stuff 
    def test_stuff(self):
        # TODO
```

The test cases from other nodes will give you a good idea what to implement as well.

**Why this is a good feature/enhancement**
Will allow CI pipeline to make sure nothing in broken when reviewing PRs

**Additional context**
n/a

**Comment by AColocho** [comment]
I can look into this. You can assign it to me.

**Comment by skekre98** [comment]
Cool, thanks!

**Comment by skekre98** [comment]
PR #83
