### ISSUE TITLE
Add more responses in InfoNode

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#79]
**Description of feature/enhancement**
There is a method in `../inference/infonode.py` called _generate_random_response_. Add more responses to the two lists present in the method.

**Description of implementation**
https://github.com/skekre98/NBA-Search/blob/9cd44d4e61972d0200b19567389e17564029fee6/inference/infonode.py#L26-L41
Add more responses to this method.

**Why this is a good feature/enhancement**
Will make the responses less static.

**Additional context**
n/a

**Comment by skekre98** [comment]
Worked on in #81

**Comment by theillzilla** [comment]
yo ... i'll do this one. Found this tool on a hacktoberfest list and im super into it.  How many more responses do you want?

**Comment by skekre98** [comment]
@theillzilla That would be awesome! Can you add 7 more responses to each list? Was hoping to have at least 10 different responses in each list before random selection. I'll go ahead and assign this issue over to you.

**Comment by AColocho** [comment]
Any way I can help with this as well?

**Comment by skekre98** [comment]
@AColocho I don't think this would require the attention of multiple people, but if you are interested in working with InfoNode take a look at #78

**Comment by skekre98** [comment]
@theillzilla any update on this issue?

**Comment by AColocho** [comment]
@skekre98 I'm still happy to help with this if you need me to.

**Comment by skekre98** [comment]
@AColocho sure, please take this up! I'll go ahead and assign this to you.
