### ISSUE TITLE
Filter out queries that have not been classified as "info" if non-NBA

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#80]
**Description of feature/enhancement**
There is a function in `../modules/analysis.py` called _isNBA_ which can be used to determine if a query is NBA related. 

If the function flags query as unsure return:
https://github.com/skekre98/NBA-Search/blob/9cd44d4e61972d0200b19567389e17564029fee6/data/text_data.py#L35

If the function flags query as nonNBA return:
https://github.com/skekre98/NBA-Search/blob/9cd44d4e61972d0200b19567389e17564029fee6/data/text_data.py#L38

**Description of implementation**
Convert response function in _InferenceNetwork_ to something along the lines of:
```python
if node type is info:
    node = InfoNode()
else:
    flag = isNBA(query)
    if flag is unsure:
        return unsure response
    elif flag is non-nba:
        return non_NBA reponse

if node type is stat:
    ....

node.load_query(query)
return node.response()
```

**Why this is a good feature/enhancement**
Will filter out queries NBA nodes can't handle.

**Additional context**
n/a

**Comment by wenderzxavier** [comment]
Can I work on this?

**Comment by skekre98** [comment]
@wenderzxavier sure thanks, will go ahead an assign this to you.

**Comment by wenderzxavier** [comment]
I removed my assignment. 
I had a problem with my machine, I will be unavailable for a few days to open the PR.

**Comment by z-siddiqi** [comment]
Hey,

I've been working on this and would like to be assigned it. For the sake of testing, what kind of query results in an unsure response? Also where do you want me to put the tests for it, within the Analysis API tests or a new class?

**Comment by skekre98** [comment]
@z-siddiqi thanks for looking into testing as well. Let's create a new class for testing the inference network since one does not exist as of today. To be honest it doesn't really matter if queries are classified as unsure or non-nba since these are both handled the same way. For testing, let's handle these type of scenarios:

- Query was incorrectly classified as `stat`, _InferenceNetwork_ should return unsure or non-nba.
- Query was incorrectly classified as `rank`, _InferenceNetwork_ should return unsure or non-nba.
- *Note*: No need to handle this for `info`. InfoNode has its own error handling.

**Comment by skekre98** [comment]
@z-siddiqi really great work! I've requested some minor changes to promote good practices.

**Comment by z-siddiqi** [comment]
Yeah those changes were a good idea, I've made them.
