### ISSUE TITLE
TableBuilder display error

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#84]
**Describe the bug**
The TableBuilder at `../lab/table_builder.py` is building the plot incorrectly. When displaying the table, the axes are still showing. The entire table is also at the bottom of the display and all rows are not viewable.

**To Reproduce**
1. Clone repo locally
2. `./setup.sh`
3. `python visualize.py`

**Expected behavior**
This should only display the table and all the rows. Ideally in the middle of the display.

**Screenshots**
![Screen Shot 2020-10-22 at 10 09 56 PM](https://user-images.githubusercontent.com/18124349/96958807-56a09c80-14b3-11eb-8d36-89a8f5e71929.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: n/a
 - Version: latest

**Additional context**
It is likely this block of code that needs fixing:
https://github.com/skekre98/NBA-Search/blob/39b7ceb873ad5ac1b3da1de073a85fd67193cd41/lab/table_builder.py#L14-L17

**Comment by samin-batra** [comment]
Hey @skekre98 I worked on creating this function, I can help with this bug.

**Comment by z-siddiqi** [comment]
Hey, 

This is just a case of turning the axis off and setting the table location to center, something like this:

`self.plt.axis('off')`
`self.plt.table(loc='center',cellLoc='center',cellText=self.cell_txt,colLabels=self.column_labels)`

![Figure_1](https://user-images.githubusercontent.com/57043176/97160042-b0cf8500-1773-11eb-935f-8f40c25a9a9d.png)
