### ISSUE TITLE
Implement get_game_adv_stats

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#85]
**Description of feature/enhancement**
Implement a function to scrape the advanced statistics from and NBA game link. This function will be very similar to `get_game_stats` only difference being you'll be scraping a different table. A lot of the code is already implemented.
![Screen Shot 2020-10-23 at 4 57 10 PM](https://user-images.githubusercontent.com/18124349/97062799-5f47b000-1551-11eb-93ec-022b2a0feeaa.png)

**Description of implementation**
This function should use BeautifulSoup to scrape all the data for both team from the advanced stats table on the webpage.
ex. https://www.basketball-reference.com/boxscores/202009300LAL.html.

The input and output of the function are defined in the function comments. Refer to `get_game_stats`, most of the code you'll need has already been implemented.

**Why this is a good feature/enhancement**
Will allow advanced stats to be scraped from game link.

**Additional context**
n/a

**Comment by danhendrix** [comment]
OK if I take a stab at it?

**Comment by skekre98** [comment]
@danhendrix thanks, that would be great. You can find the method here:
https://github.com/skekre98/NBA-Search/blob/17d38f5a9ef99e11cd73c6241402103a7bd8880f/modules/scraper.py#L376-L395

**Comment by skekre98** [comment]
Merged in #90
