### ISSUE TITLE
Implement agglomerative clustering until target number of clusters is reached

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#97]
**Description of feature/enhancement**
This function should create _c_ clusters via agglomerative clustering in the _ClusterStore_.

**Description of implementation**
https://github.com/skekre98/NBA-Search/blob/0564a752c77a7c420890c44e6873c53111251fe5/inference/cluster_store.py#L84
This function should follow a [Heirarchical Approach](https://www.datanovia.com/en/lessons/agglomerative-hierarchical-clustering/) and start of treating each object as a singleton cluster.

**Why this is a good feature/enhancement**
Would be nice to see how different clustering algorithms perform on different sets of data.

**Additional context**
n/a

**Comment by amangal2000** [comment]
I would like to try this!

**Comment by skekre98** [comment]
@amangal2000 Sure! That would be greatly appreciated.
