### ISSUE TITLE
Implement function to find average similarity between clusters in ClusterStore

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#98]
**Description of feature/enhancement**
This function should find the average similarity between all the clusters in the _ClusterStore_.

**Description of implementation**
https://github.com/skekre98/NBA-Search/blob/0564a752c77a7c420890c44e6873c53111251fe5/inference/cluster_store.py#L89
This function should set `self.avg_similarity` to the calculated value and shouldn't return anything. The metric for similarity is up to developer, but I would recommend something simple for now such as cosine or jaccard similarity.

**Why this is a good feature/enhancement**
Would be nice to have a way to analyze how well clustering jobs are performing. 

**Additional context**
n/a

**Comment by amangal2000** [comment]
Hi! I would like to work on this. I am a little busy with school and will have to learn some data science concepts to get going on this, so it may take me a few weeks if thats okay.

**Comment by skekre98** [comment]
@amangal2000 Sure! That would be great. Please take your time.
