### ISSUE TITLE
Migrate inference tests

### ISSUE THREAD

**Issue by skekre98** [skekre98/NBA-Search#99]
**Description of feature/enhancement**
The _test.py_ file is getting a bit cluttered, move the inference related tests to their own file called _inference_tests.py_.

**Description of implementation**
Migrate the _TestStatNode_, _TestRankNode_, _TestInfoNode_, and _TestInferenceNetwork_ classes into the new file.

**Why this is a good feature/enhancement**
Would be easier to keep track of tests if they are in their own separate files.

**Additional context**
Do not delete test.py or your PR will fail during integration. Leave test.py as is and only migrate the required test classes to the new file.

**Comment by z-siddiqi** [comment]
I can take this one.

**Comment by Sameer-Mann** [comment]
@z-siddiqi i have opened a pull request for the same.

**Comment by skekre98** [comment]
@Sameer-Mann thanks for taking all three issues up! Next time can you wait for the issue to be assigned to you so we can avoid confusion 👍 . I have linked your PR too all three issues for now.
